name 'npm_proxy_cache'
maintainer 'vladimir'
maintainer_email 'vladimir4862@gmail.com'
license 'all_rights'
description 'Installs/Configures npm_proxy_cache'
long_description 'Installs/Configures npm_proxy_cache'
version '0.1.0'
source_url 'https://github.com/vladimir4862/chef/edit/master/npm_proxy_cache' 
