name 'npm_proxy_cache'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures npm_proxy_cache'
long_description 'Installs/Configures npm_proxy_cache'
version '0.1.0'
